name: 'Transform and Inline Mermaid'
description: 'transform and Inline Mermaid charts in SVG images!'
branding:
  icon: at-sign
  color: blue
inputs:
  file-regex:
    description: The regex used to search for files where mermaid graph inlining will be applied
    required: true
    default: "^index\\.html?$"

  root-folder:
    description: The root folder used to search the files that match the file-regex passed
    required: true
    default: "build"

  config-file:
    description: The file used to configure mermaid (toml)
    required: true
    default: "config.toml"
runs:
  using: "composite"
  steps:
    - name: Install Dependecies
      working-directory: ${{github.action_path}}
      run: npm install
      shell: sh

    - name: Inline charts
      run: fileRegex=${{inputs.file-regex}} rootFolder=${{inputs.root-folder}} configFile=${{inputs.config-file}} node ${GITHUB_ACTION_PATH}/index.js
      shell: sh
