name: 'Transform and Inline Mermaid'
description: 'transform and Inline Mermaid charts in SVG images!'
branding:
  icon: at-sign
  color: blue
inputs:
  root-folder:
    description: The root folder used to search the files that match the file-regex and css-file-regex passed
    required: true
    default: "build"

  file-regex:
    description: The regex used to search for files where mermaid graph inlining will be applied. The regex is applied to the relative path! 
    required: true
    default: "index\\.html?$"

  config-file:
    description: The file used to configure mermaid (toml)
    required: true
    default: "config.toml"

  config-path-regex:
    description: The JSON Path regex to get the mermaid configuration, please refear to https://github.com/JSONPath-Plus/JSONPath
    required: true
    default: "$.params.reveal_hugo.mermaid[0]"

  css-file-regex:
    description: The regex used to search the css file. Only on CSS file can be used.
    default: css\\/.*\\\.css$

runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4.1.0
      with:
        node-version-file: package.json
    - name: Install Dependecies
      working-directory: ${{github.action_path}}
      run: npm install
      shell: sh
    
    - name: Inline charts
      run: fileRegex=${{inputs.file-regex}} rootFolder=${{inputs.root-folder}} configFile=${{inputs.config-file}} cssRegex=${{inputs.css-file-regex}} configPath="${{inputs.config-path-regex}}" node ${GITHUB_ACTION_PATH}/index.js
      shell: sh
